apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nginx-www

  annotations:
    nfs.io/storage-path: "nginx-www"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi